### ISSUE TITLE
Use waitForAbort() in place of sleep() to ensure fast shutdown or disable

### ISSUE THREAD

**Issue by MilhouseVH** [phil65/plugin.video.amazon65#1]
I've noticed that disabling this addon, or shutting down the system while the addon is active, can take several seconds, usually exceeding the 5 second limit before addons are forcibly terminated (memory leaked etc. etc.).

The addon should use [`waitForAbort()`](http://kodi.wiki/view/Service_add-ons) in place of `sleep()`.

The following should definitely be replaced:

https://github.com/phil65/plugin.video.amazon65/blob/master/service.py#L55
https://github.com/phil65/plugin.video.amazon65/blob/master/service.py#L63

In theory `waitForAbort()` can be used anywhere the addon is sleeping to facilitate quick shutdown/disable - if it returns `true` the add-on is aborting.

**Comment by phil65** [comment]
I know i know :)
Didnt have the time yet to  clean up all the mess from the original script.

**Comment by phil65** [comment]
should be fixed with https://github.com/phil65/plugin.video.amazon65/commit/9d5498e085f1235e572e0858afc0276c0723a4f0 (untested)

**Comment by MilhouseVH** [comment]
Thanks - it's working well, kind of. I say kind off, as there's some unusual behaviour which may not be specific to this addon.

1. If the addon is already enabled when the system is booted, when the "Disable" button is pressed the service shuts down quickly. This is good - thanks.

2. Having disabled the addon in #1, if the addon is again enabled the service doesn't appear to start up properly, and clicking "Disable" a second time results in the message "script didn't stop in 5 seconds - let's kill it" appearing in the log, suggesting the add-on isn't shutting down quickly.

3. Sometimes, maybe 1 in 2 attempts, when clicking the "Disable" button the Kodi GUI will completely freeze, which is probably due to a deadlock somewhere. Maybe one for @tamland? If I attach strace, all I see is:
```
futex(0x74600600, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, ffffffff
```
If I kill the frozen kodi.bin with `kill -SIGSEGV $(pidof kodi.bin)`, this is the resulting crashlog: http://sprunge.us/GRBb

**Comment by tamland** [comment]
Service addons deadlocking on disable has been well known for years unfortunately. Best not use it and restart kodi instead:\

**Comment by MilhouseVH** [comment]
OK thanks, fortunately it's not something I do often, only when testing... :)

**Comment by phil65** [comment]
The general approach of this add-on is kind of brain-dead... it consists of a database (put into a separate add-on), the plugin part  and a service part to keep the db up-to-date. I will try to get rid of most of that if time allows.
